# Generated by Django 5.1.6 on 2025-02-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0002_alter_category_image_alter_emogi_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emogi',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
