# Generated by Django 5.1.6 on 2025-03-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0004_category_user_id_emogi_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='emogi',
            old_name='user_id',
            new_name='user',
        ),
    ]
