# Generated by Django 5.1.6 on 2025-03-01 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0005_rename_user_id_category_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emogi',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emoji.category'),
        ),
    ]
