# Generated by Django 5.1.6 on 2025-03-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0006_alter_emogi_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emogi',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
