# Generated by Django 5.1.6 on 2025-02-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emoji', '0003_alter_emogi_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('emoji_id', models.ManyToManyField(to='emoji.emogi')),
            ],
        ),
    ]
